name: FurnitureMaker
version: 1.6
description: Create simple your own Minecraft Furnitures
author: Ste3et_C0st
website: http://dicecraft.de
depend: [FurnitureLib]
main: de.Ste3et_C0st.DiceFurnitureMaker.main